### ISSUE TITLE
Unable to reconstruct a pyramid with custom amount of orientations

### ISSUE THREAD

**Issue by tdelanversin** [LabForComputationalVision/pyrtools#13]
I'm trying to construct a steerable frequency pyramid of order 3 but with n orientations (usually around 16), but once I get the `steer_coeffs()` output and modify it to my needs, I can't add it back to the pyramid to do the `recon_pyr()`.

Is there a current method to solve this without having to overload the __init__ function?

If not, some potential solutions could be:
- Let users choose num_orientations when building the pyramid,
- Let the `recon_pyr()` accept coefficients as input

**Comment by tdelanversin** [comment]
Additionally, when testing out a modified version where the number of orientations could be decided at creation time with a parameter, I found that the magnitude of the resulting images in each step of the pyramid were different when calculated through `steer_coeffs()` or the default calculation.

Is this intended? What is the difference?

**Comment by billbrod** [comment]
You're correct, there is no way to do this with the current implementation. I think the preferred way to handle this would be to chance `recon_pyr` to accept the coefficients as an optional input, defaulting to the attribute if they're not passed, rather than allowing the number of orientations and order to both be set at initialization.

This is how we handle it in the steerable pyramid implemented in [plenoptic](https://github.com/LabForComputationalVision/plenoptic), which is equivalent to the one implemented here, but done using pytorch, rather than numpy. If pytorch is acceptable for your intended use, I'd recommend using plenoptic instead of pyrtools, as it's being more actively maintained, in addition to having the feature you're looking for.

If you do want to continue using the pyrtools implementation, a PR making the change to `recon_pyr` would be appreciated (and you could base it off the one in plenoptic)! I'm not sure when I'd have time to get around to implementing it myself.

As for your second problem, I don't think I can figure out why that's happening without seeing how you implemented the change to the initialization method. But again, I think the better (and simpler) way to do it would be to chance the `recon_pyr` method.

**Comment by tdelanversin** [comment]
Thank you, I will look into plenoptic then. 

I'll also look into implementing the functionality into pyrtools directly.

As for how I coded the quick fix for the `num_orientations`, I did:
```
class SteerablePyramidFreq(SteerablePyramidBase):

    def __init__(self, image, height='auto', order=3, num_orientations=None, twidth=1, is_complex=False):
        # in the Fourier domain, there's only one choice for how do edge-handling: circular. to
        # emphasize that thisisn'ta choice, we use None here.

        '''
        more code here, abreviated for simplicity
        '''

        if num_orientations is not None:
            self.num_orientations = int(num_orientations)
        else:
            self.num_orientations = int(order + 1)
```

**Comment by tdelanversin** [comment]
Alright, that makes a lot of sense, thank you :+1:

**Comment by billbrod** [comment]
@tdelanversin are you okay with closing this issue? you can reopen it if you want to make the modifications we discussed.
