### ISSUE TITLE
如何处理NameError: name 'lib' is not defined错误

### ISSUE THREAD

**Issue by FUGUILuo** [LabForComputationalVision/pyrtools#26]
在Windows系统下调用pyrtools包，其中的wrapper.py文件中使用了lib
python版本为3.8   pyrtools版本为1.0.2

**Comment by billbrod** [comment]
This appears to be the same (or related?) lack-of-Windows-support issues that was reported in #18. It should now be fixed with pull request #27. If you try re-installing the package (either from source or pip, version 1.0.3), it should install without a problem.

I'm going to close this issue, please re-open if this installing the newest version of pyrtools does not fix your problem.

In the future, please use our bug report template for opening an issue like this.
